name = "albertbf-blog"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "bun run build"

[assets]
directory = "./dist"

[vars]
ENVIRONMENT = "production"

[env.production]
routes = [
  { pattern = "albertbf.com/*", custom_domain = true }
]

# For local development
[env.development]
vars = { ENVIRONMENT = "development" }